package/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length, Email, EqualTo
from package.core.models import User
from flask_babel import _, lazy_gettext as _l
from flask import request



class EditProfileForm(FlaskForm):
	username = StringField(_l('Username'), validators=[DataRequired()])
	about_me = TextAreaField(_l('About me *'), validators=[Length(min=0, max=140)])
	email = StringField(_l('Email'), validators=[DataRequired(), Email()])
	password = PasswordField(_l('Password *'))
	password2 = PasswordField(
		_l('Repeat Password *'), validators=[EqualTo('password')])
	submit = SubmitField(_l('Submit'))

	def __init__(self, original_username, *args, **kwargs):
		super(EditProfileForm, self).__init__(*args, **kwargs)
		self.original_username = original_username

	def validate_username(self, username):
		if username.data != self.original_username:
			user = User.query.filter_by(username=self.username.data).first()
			if user is not None:
				raise ValidationError(_('Please use a different username.'))



class EditProfileFormOther(FlaskForm):
	username = StringField(_l('Username'), validators=[DataRequired()])
	about_me = TextAreaField(_l('About me *'), validators=[Length(min=0, max=140)])
	email = StringField(_l('Email'), validators=[DataRequired(), Email()])
	submit = SubmitField(_l('Submit'))

	def __init__(self, original_username, *args, **kwargs):
		super(EditProfileForm, self).__init__(*args, **kwargs)
		self.original_username = original_username

	def validate_username(self, username):
		if username.data != self.original_username:
			user = User.query.filter_by(username=self.username.data).first()
			if user is not None:
				raise ValidationError(_('Please use a different username.'))



class PostForm(FlaskForm):
	post = TextAreaField(_l('Say something:'), validators=[
		DataRequired(), Length(min=1, max=140)])
	submit = SubmitField(_l('Submit'))



class GroupForm(FlaskForm):
	user_admin = BooleanField("set admin status; true/false")
	submit = SubmitField(_l('Submit'))



class SearchForm(FlaskForm):
	q = StringField(_l('Search'), validators=[DataRequired()])
	
	def __init__(self, *args, **kwargs):
		if 'formdata' not in kwargs:
			kwargs['formdata'] = request.args
		if 'csrf_enabled' not in kwargs:
			kwargs['csrf_enabled'] = False
		super(SearchForm, self).__init__(*args, **kwargs)

package/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from package.blueprints.main import routes

package/blueprints/main/routes.py
from flask import render_template, flash, redirect, url_for, request, g, current_app, g
from package.core import db
from .forms import EditProfileForm, PostForm, GroupForm, SearchForm
from flask_login import current_user, login_user, logout_user, login_required
from package.core.models import User, Post
from datetime import datetime
from flask_babel import _, get_locale
from . import bp



@bp.before_app_request
def before_request():
	if current_user.is_authenticated:
		current_user.last_seen = datetime.utcnow()
		db.session.commit()
		g.search_form = SearchForm()
	g.locale = str(get_locale())



@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(body=form.post.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash(_('Your post is now online!'))
		return redirect(url_for('main.index'))
	page = request.args.get('page', 1, type=int)
	posts = current_user.followed_posts().paginate(
		page, current_app.config['POSTS_PER_PAGE'], False)
	next_url = url_for('main.explore', page=posts.next_num) if posts.has_next else None
	prev_url = url_for('main.explore', page=posts.prev_num) if posts.has_prev else None
	return render_template('index.html', title=_('Home Page'), form=form, posts=posts.items,
		next_url=next_url, prev_url=prev_url)



@bp.route('/user/<username>', methods=['GET', 'POST'])
@login_required
def user(username):
	user = User.query.filter_by(username=username).first_or_404()
	page = request.args.get('page', 1, type=int)
	posts = user.posts.order_by(Post.timestamp.desc()).paginate(
		page, current_app.config['POSTS_PER_PAGE'], False)
	next_url = url_for('main.explore', username=user.username, page=posts.next_num) \
		if posts.has_next else None
	prev_url = url_for('main.explore', username=user.username, page=posts.prev_num) \
		if posts.has_prev else None
	form = GroupForm()
	if form.validate_on_submit():
		user.user_admin = form.user_admin.data
		db.session.commit()
		db.session.commit()
		flash(_('%(user1)s is admin: %(boolu)s', user1=user.username, boolu=form.user_admin.data))
		return redirect(url_for('main.user', username=user.username))
	return render_template('user.html', user=user, form=form, posts=posts.items,
		next_url=next_url, prev_url=prev_url, app=current_app)



@bp.route('/edit_profile/', methods=['GET', 'POST'])
@login_required
def edit_profile():
	form = EditProfileForm(current_user.username)
	user = current_user
	if form.validate_on_submit():
		user.username = form.username.data
		user.about_me = form.about_me.data
		user.email = form.email.data
		if len(form.password.data) > 0:
			user.set_password(form.password.data)
		db.session.commit()
		flash(_('Your changes have been saved.'))
		return redirect(url_for('main.edit_profile'))
	elif request.method == 'GET':
		form.username.data = user.username
		form.email.data = user.email
		form.about_me.data = user.about_me
	return render_template('edit_profile.html', title='Edit Profile', user=user, form=form)



@bp.route('/edit_profile/<username>', methods=['GET', 'POST'])
@login_required
def edit_profile_other(username):
	if not current_user.is_admin():
		return redirect(url_for('main.edit_profile'))
	form = EditProfileForm(username)
	user = User.query.filter_by(username=username).first_or_404()
	if form.validate_on_submit():
		user.username = form.username.data
		user.about_me = form.about_me.data
		user.email = form.email.data
		db.session.commit()
		flash(_('Your changes have been saved.'))
		return redirect(url_for('main.user', username=user.username))
	elif request.method == 'GET':
		form.username.data = user.username
		form.email.data = user.email
		form.about_me.data = user.about_me
	return render_template('edit_profile.html', title='Edit Profile', user=user, form=form)



@bp.route('/follow/<username>')
@login_required
def follow(username):
	user = User.query.filter_by(username=username).first_or_404()
	if user is None:
		flash(_('User %(user1)s not found.', user1=username))
		return redirect(url_for('main.index'))
	if user == current_user:
		flash(_('You cannot follow yourself!'))
		return redirect(url_for('main.user', username=user))
	current_user.follow(user)
	db.session.commit()
	flash(_('You are following %(user1)s now!', user1=username))
	return redirect(url_for('main.user', username=username))



@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
	user = User.query.filter_by(username=username).first_or_404()
	if user is None:
		flash(_('User %(user1)s not found.', user1=username))
		return redirect(url_for('main.index'))
	if user == current_user:
		flash(_('You cannot unfollow yourself!'))
		return redirect(url_for('main.user', username=username))
	current_user.unfollow(user)
	db.session.commit()
	flash(_('You are no longer following %(user1)s!', user1=username))
	return redirect(url_for('main.user', username=username))



@bp.route('/explore')
@login_required
def explore():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.timestamp.desc()).paginate(
		page, current_app.config['POSTS_PER_PAGE'], False)
	return render_template('index.html', title='Explore', posts=posts.items)



@bp.route('/search')
@login_required
def search():
	if not g.search_form.validate():
		return redirect(url_for('.explore'))
	page = request.args.get('page', 1, type=int)
	posts, total = Post.search(g.search_form.q.data, page,
		current_app.config['POSTS_PER_PAGE'])
	next_url = url_for('.search', q=g.search_form.q.data, page=page + 1) \
		if total > page * current_app.config['POSTS_PER_PAGE'] else None
	prev_url = url_for('.search', q=g.search_form.q.data, page=page - 1) \
		if total > 1 else None
	return render_template('search.html', title=_('Search'), posts=posts,
		next_url=next_url, prev_url=prev_url)

package/blueprints/main/templates/_post.html
	<table class="table table-hover">
		<tr>
			{% if post.author %}
			<td width='70px'>
			<a href="{{ url_for('main.user', username=post.author.username) }}">
				<img src="{{ post.author.avatar(70) }}" />
				</a>
			</td>
			<td>
				{% set user_link %}
				<a href="{{ url_for('main.user', username=post.author.username) }}">
					{% if post.author.is_admin() %}
						<span style='color:red;'>{{ post.author.username }}</span>
					{% else %}{{ post.author.username }}{% endif %}
				</a>
				{% endset %}
				{{ _('%(username)s said %(when)s',
				username=user_link, when=moment(post.timestamp).fromNow()) }}
				<br>
				{{ post.body }}
			</td>
			{% endif %}
		</tr>
	</table>

package/blueprints/main/templates/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
	{% if title %}{{ title}} - mavki{% else %}{{_('Welcome to Mavki') }}{% endif %}
{% endblock %}

{% block navbar %}
	<nav class='navbar navbar-default'>
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{{ url_for('main.index') }}">Mavki</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
				<li><a href="{{ url_for('main.index') }}">{{ _('Home') }}</a></li>
				<li><a href="{{ url_for('main.explore') }}">{{ _('Explore') }}</a></li>
				</ul>
				{% if g.search_form %}
				<form class="navbar-form navbar-left" method="get"
					action="{{ url_for('main.search') }}">
				<div class="form-group">
					{{ g.search_form.q(size=20, class='form-control',
						placeholder=g.search_form.q.label.text) }}
				</div>
				</form>
				{% endif %}
				<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_anonymous %}
				<li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>
				{% else %}
				<li><a href="{{ url_for('main.user', username=current_user.username) }}">{{ _('Profile') }}</a></li>
				<li><a href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
				{% endif %}
				{% if current_user.is_authenticated %}		
					{% if current_user.is_admin() %}
					<li><span style="color:red;">Admin</span></li>
					{% endif %}
				{% endif %}
				</ul>
			</div>
		</div>
	</nav>
{% endblock %}
{% block content %}
	<div class="container">
		{% with messages = get_flashed_messages() %}
		{% if messages %}
			{% for message in messages %}
			<div class="alert alert-info" role="alert">{{ message }}</div>
			{% endfor %}
		{% endif %}
		{% endwith %}

		{# application app_content needs to be provided in the app_content block #}
		{% block app_content %}{% endblock %}
	</div>
{% endblock %}
{% block scripts %}
	{{ super() }}
	{{ moment.include_moment() }}
	{{ moment.lang(g.locale) }}
{% endblock %}

package/blueprints/main/templates/edit_profile.html
{% extends 'base.html' %}

{% block app_content %}
	<h1>{{ _('Edit Profile') }}</h1>
	<div class='row'>
		<div class='col-md-4'>
			{{ wtf.quick_form(form) }}
		</div>
	</div>
{% endblock %}

package/blueprints/main/templates/index.html
{% extends "base.html" %}

{% block app_content %}
	{% if form %}
	<h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
	{{ wtf.quick_form(form) }}
	<br>
	{% else %}
	<h2>Explore the forum</h2>
	{% endif %}
	{% for post in posts %}
		{% include '_post.html' %}
	{% endfor %}
	<nav aria-label="...">
		<ul class="pager">
			<li class="previous{% if not prev_url %} disabled{% endif %}">
				<a href="{{ prev_url or '#' }}">
				<span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
				</a>
			</li>
			<li class="next{% if not next_url %} disabled{% endif %}">
				<a href="{{ next_url or '#' }}">
				{{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
				</a>
			</li>
		</ul>
	</nav>
{% endblock %}

package/blueprints/main/templates/search.html
{% extends "base.html" %}

{% block app_content %}
	<h1>{{ _('Search Results') }}</h1>
	{% for post in posts %}
		{% include '_post.html' %}
	{% endfor %}
	<nav aria-label="...">
		<ul class="pager">
			<li class="previous{% if not prev_url %} disabled{% endif %}">
				<a href="{{ prev_url or '#' }}">
				<span aria-hidden="true">&larr;</span>
				{{ _('Previous results') }}
				</a>
			</li>
			<li class="next{% if not next_url %} disabled{% endif %}">
				<a href="{{ next_url or '#' }}">
				{{ _('Next results') }}
				<span aria-hidden="true">&rarr;</span>
				</a>
			</li>
		</ul>
	</nav>
{% endblock %}

package/blueprints/main/templates/user.html
{% extends "base.html" %}

{% block app_content %}
	<table class="table table-hover">
		<tr>
			<td width="256px"><img src="{{ user.avatar(256) }}"></td>
			<td>
				<h1>{{ _('User') }}: {{ user.username }}</h1>
				{% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
				{% if user.last_seen %}
				<p>{{ _('Last seen on') }}: {{ moment(user.last_seen).format('LLL') }}</p>
				{% endif %}
				<p>{{ _('%(count)d followers', count=user.followers.count()) }}, {{ _('%(count)d following', count=user.followed.count()) }}</p>
				{% if user == current_user %}
				<p><a href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a></p>
				{% elif not current_user.is_following(user) %}
				<p><a href="{{ url_for('main.follow', username=user.username) }}">{{ _('Follow') }}</a></p>
				{% else %}
				<p><a href="{{ url_for('main.unfollow', username=user.username) }}">{{ _('Unfollow') }}</a></p>
				{% endif %}
			</td>
			{% if app.config['HIRE'] %}
			<td>
				{% if current_user.is_admin() %}
					{% if user == current_user %}
						<span style='color:red;'>BE CAREFUL, YOU CANNOT RE-ADMIN YOURSELF!</span>
					{% endif %}
					<form action='' method='post'>
						{{ form.hidden_tag() }}
						<p>{{ form.user_admin() }} {{ form.user_admin.label }}</p>
						<p>{{ form.submit() }}</p>
					</form>
				{% endif %}
			</td>
			{% endif %}
		</tr>
	</table>
	{% for post in posts %}
		{% include '_post.html' %}
	{% endfor %}
	<nav aria-label="...">
		<ul class="pager">
			<li class="previous{% if not prev_url %} disabled{% endif %}">
				<a href="{{ prev_url or '#' }}">
				<span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
				</a>
			</li>
			<li class="next{% if not next_url %} disabled{% endif %}">
				<a href="{{ next_url or '#' }}">
				{{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
				</a>
			</li>
		</ul>
	</nav>
{% endblock %}